### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Implementig class

### ISSUE THREAD

**Issue by ghost** [bmc/javautil#17]
Hello,
ich get and IncompatibleClassChangeError on the first line of following code.

```
ClassFinder finder = new ClassFinder();
ClassFilter filter = new AndClassFilter(new SubclassClassFilter(Tool.class));
Collection<ClassInfo> foundClasses = new ArrayList<>();
finder.findClasses(foundClasses, filter);
```

Full error:

```
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by bmc** [comment]
I've seen this happen in the [Scala version of this class-util code](https://github.com/bmc/classutil). As noted in [Issue #19](https://github.com/bmc/classutil/issues/19) there:

> This issue seems caused by the presence of ASM 3.x in the classpath, causing a conflict. In this earlier version, ClassVisitor was an interface instead of an abstract class.
>
> The common way to go seems to be shadowing asm, relocating its package to something like `org.clapper.classutil.shadow.asm`.

I'm not inclined to shadow ASM in this library, so you might try the solutions outlined in that issue.
